// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package provider

import (
	"github.com/CloudStriver/cloudmind-system/biz/adaptor"
	"github.com/CloudStriver/cloudmind-system/biz/application/service"
	"github.com/CloudStriver/cloudmind-system/biz/infrastructure/config"
	"github.com/CloudStriver/cloudmind-system/biz/infrastructure/mapper/notification"
)

// Injectors from wire.go:

func NewSystemServerImpl() (*adaptor.SystemServerImpl, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	iNotificationMongoMapper := notification.NewNotificationModel(configConfig)
	systemServiceImpl := &service.SystemServiceImpl{
		MongoMapper: iNotificationMongoMapper,
	}
	systemServerImpl := &adaptor.SystemServerImpl{
		Config:        configConfig,
		SystemService: systemServiceImpl,
	}
	return systemServerImpl, nil
}
